trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: nodeVersion
    value: "18.x"
  - group: QA-Automation-Variables

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build Job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: "Install Node.js"

          - script: |
              npm install
            displayName: "Install dependencies"

          - script: |
              echo "REACT_APP_QA_TOUCH_API_TOKEN=$(QATOUCH_API_TOKEN)" >> .env
            displayName: "Set environment variables"

          - script: |
              npm run build
            displayName: "Build application"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "build"
              artifactName: "drop"
            displayName: "Publish build artifacts"

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: "Deploy to Azure Static Web Apps"
        environment: "staging"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureStaticWebApp@0
                  inputs:
                    app_location: "/"
                    api_location: ""
                    output_location: "build"
                    skip_app_build: true
